[tool.poetry]
name = "webhook_metrics"
version = "0.1.0"
description = ""
authors = ["NotAFile <nota@notafile.com>"]

[tool.poetry.dependencies]
python = "*"
requests = "^2.19"
prometheus_client = "^0.3.1"

[tool.poetry.dev-dependencies]
black = "^18.3-alpha.0"
